#!/bin/bash

function configTerminatorLoc() {

	apt-get install -y terminator ttf-wqy-microhei

	if [ -d $HOMT/.config/terminator/config ]; then
		mv $HOME/.config/terminator/config $HOME/.config/terminator/config.bak
	else
		mkdir -p $HOME/.config/terminator
	fi
	cp ./terminator_config $HOME/.config/terminator/config
}


configTerminatorLoc
