#!/bin/bash

function config() {

    git clone https://github.com/clvv/fasd.git
    cd fasd
    sudo make install

    cd ~
    touch ~/.zhistory
    chown $USER ~/.zhistory
    command -v zsh | sudo tee -a /etc/shells
    chsh -s "$(command -v zsh)" "${USER}"
    su $USER
}


sudo cat ./hosts >> /etc/hosts
sudo apt install -y libncurses5-dev zsh

sudo wget -nv -O - https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh

cp zshrc ~/.zshrc
config
