#!/bin/bash

function zshInstall() {
    zshloc=$(which zsh)
    if [ $zshloc = /usr/bin/zsh ]; then
        echo -e "系统监测已经安装zsh"
    else
		apt install -y libncurses5-dev
		wget https://sourceforge.net/projects/zsh/files/zsh/5.6.2/zsh-5.6.2.tar.xz
		xz -d zsh-5.6.2.tar.xz
		tar -xvf zsh-5.6.2.tar
		cd zsh-5.6.2
		./configure
		make install
    fi
}

function zimInstall() {
	git clone --recursive https://github.com/Eriner/zim.git ${ZDOTDIR:-${HOME}}/.zim
	for f in ${HOME}/.zim/templates/*; do cp $f ${HOME}/.$(basename $f); done
}

function config() {
	cp zshrc ~/.zshrc

	git clone https://github.com/clvv/fasd.git
	cd fasd
	make install

	exec $SHELL
	chsh -s $(which zsh)
	exit
}


zshInstall
zimInstall
config
