#
# User configuration sourced by interactive shells
#

# Caps Lock >> Esc
#xmodmap ~/.Xmodmap >/dev/null 2>&1

# Define zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# tmux cmd
alias nt='tmux new -t'
alias at='tmux a -t'
alias vim='nvim'
alias vi='nvim'
alias x='xmodmap ~/.Xmodmap'

alias cl='clear'
alias tailf='tail -f'
alias curl='curl -H "Content-Type:application/json"'

# pyenv
if [[ -s $HOME/.pyenv ]]; then
	export PYENV_ROOT="$HOME/.pyenv"
	export PATH="$PYENV_ROOT/bin:$PATH"
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

# 禁用字节码（.pyc）文件
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PYTHONDONTWRITEBYTECODE=1

# ttygif 配置
# export WINDOWID=$(xdotool getwindowfocus)
## ttyrec xxxx 
## ttygif xxxx -f

if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi
# fasd
eval "$(fasd --init auto)"
# alias a='fasd -a' # any
# alias s='fasd -si' # show / search / select
# alias d='fasd -d' # directory
#alias f='fasd -f' # file
# alias sd='fasd -sid' # interactive directory selection
# alias sf='fasd -sif' # interactive file selection
alias z='fasd_cd -d' # cd, same functionality as j in autojump
# alias zz='fasd_cd -d -i' # cd with interactive selection

# export LC_CTYPE=en_US.UTF-8
# export LC_ALL=en_US.UTF-8
