#!/bin/bash

function checkVimVersion() {
	vimloc=$(which vim || which vi)
	while [ -L $vimloc ]; do
		vimloc=$(ls -l $vimloc | sed -r 's/.+-> ([^ ]+).*/\1/')
	done
	vimViersion=$(echo $vimloc | sed -r 's/.+vim\.(.+)/\1/')
	echo -e "\033[32m vim version: $vimViersion\033[0m"
	if [ $vimViersion = basic ]; then
		return 0
	else
		return 1
	fi
}

function configVimBasic() {
	if checkVimVersion; then
		echo -e '\033[32m无需升级VIM\033[0m'
	else
		echo -e '\033[32m升级VIM\033[0m'
		sudo apt-get remove vim-tiny vim-commoin
		sudo apt-get install -y vim
	fi
	sudo apt-get install -y git
	if [ -f $HOME/.vim/bundle/Vundle.vim ]; then
		echo -e '已经安装Vundle管理工具'
	else
		echo -e '安装Vundle管理工具'
		git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
	fi

	echo -e '\033[32m配置用户的vim配置文件.vimrc\033[0m'
	cat ./vimBasicConf.vimrc >> $HOME/.vimrc
	cat ./vimrc.bundles >> $HOME/.vim/vimrc.bundles
	mkdir -p $HOME/.vim/colors
	cp ./joit.vim $HOME/.vim/colors/
}

function configYouCompleteMe() {
	sudo apt-get install -y build-essential cmake
	sudo apt-get install -y python-dev python3-dev
	sudo apt-get install -y exuberant-ctags
}

function makeYouCompleteMe() {
	echo -e "\033[32m编译自动补全插件YouCompleteMe\033[0m"
	cd $HOME/.vim/bundle/YouCompleteMe
	./install.py --all
	echo -e "\033[32m编译完成！\033[0m"
	# 注释掉.ycm_extra_conf.py中的选项
	cp ./third_party/ycmd/cpp/ycm/.ycm_extra_conf.py $HOME/.ycm_extra_conf.py
	num=$(sed -n "/final_flags.remove/=" $HOME/.ycm_extra_conf.py)
	sed -i "$(expr $num - 1),$(expr $num + 2) s/^/#/" $HOME/.ycm_extra_conf.py
	# 添加库所在的flags
	num=$(sed -n "/^]/=" $HOME/.ycm_extra_conf.py)
	gcc_version=$(sed -r "s/.+gcc version ([0-9\.]+).+/\1/" /proc/version)
	sed -i "$num i# add by qiuyu\n'-isystem',\n'/usr/include',\n'-isystem',\n'/usr/include/x86_64-linux-gnu',\n'-isystem',\n'/usr/include/c++/$gcc_version',\n'-isystem',\n'/usr/include/c++/$gcc_version/backward',\n'-isystem',\n'/usr/include/x86_64-linux-gnu/c++/$gcc_version',\n'-isystem',\n'/usr/local/include'," $HOME/.ycm_extra_conf.py
	cd $HOME
}

configVimBasic
configYouCompleteMe

echo -e "\033[32m正在进行插件安装……\033[0m"

vim +PluginInstall +qall 

makeYouCompleteMe
