#!/bin/bash

sudo apt install neovim xclip ack curl

mkdir -p $HOME/.config/nvim
mkdir -p $HOME/.config/nvim/colors
echo '[flake8]\nmax-line-length = 120' > $HOME/.config/flake8

curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
cp ./jellybeans.vim $HOME/.config/nvim/colors
cp ./init.vim $HOME/.config/nvim
cp ./vimrc.bundles $HOME/.config/nvim

nvim +PlugInstall +qall
